name: tests

on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          restore-keys: |
            npm-feature-${{ hashFiles('package-lock.json') }}
            npm-feature-
            npm-
      
      - name: Install dependencies
        run: npm i
      
      - name: Test
        run: npm run test